//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bibliothèque
    {
        public int id_bibli { get; set; }
        public string adresse_bibli { get; set; }
        public string tel_bibli { get; set; }
    }
}
