//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpruntsLivres
    {
        public int id_emprunt_l { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_livre { get; set; }
        public System.DateTime date_emprunt_l { get; set; }
        public Nullable<System.DateTime> date_retour_l { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Livres Livres { get; set; }
    }
}
