//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothèque.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliothèqueEntities : DbContext
    {
        public BibliothèqueEntities()
            : base("name=BibliothèqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bibliothèque> Bibliothèque { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<EmpruntsFilms> EmpruntsFilms { get; set; }
        public virtual DbSet<EmpruntsLivres> EmpruntsLivres { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Livres> Livres { get; set; }
    }
}
